### ISSUE TITLE
个人使用总结

### ISSUE THREAD

**Issue by CCKNBC** [Colsrch/hexo-offline-popup#1]
因为我使用的butterfly主题，然后估计是pjax的原因，我大致懂原理，但使用过程中会加上index.html还有时间戳版本号之类的（关掉了根目录的开关），有没有办法去掉，我虽然目前只让他在posts目录下监控html实现了缓存比较小的更新提示，但是希望有一天可以实现这个功能，这样我也愿意添加更多类型的缓存来提高访问速度
还有就是更新弹窗好看是好看，但我想点击x刷新的话对一般逻辑可能不是那么友好，（个人觉得x就该是关闭这个通知），希望把刷新功能赋给刷新生效。
以上都是个人看法，望开发者回复

> 抱歉，两周前没发现这条issue邮件，今天发现close邮件才知道，这里回答下你的这几个问题
> 1、有关时间戳这些：这个是只会在食用pjax的情况下出现，因为每个版本的缓存都有一个sw缓存编号，而由于pjax的特性，这个缓存编号便会显示出来，不用pjax是没有缓存编号的。
> 2、它的缓存范围是可以自己控制的，修改这里面的就可以
> 
> ```yaml
> staticFileGlobs:
>   - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
> ```
> 
> 3、关于第三个，我仔细想了想，直接刷新确实不太好，感谢您的建议

谢谢，这个插件我会跟进的，虽然主题自带通过workbox实现了pwa和更新通知，但是还是想试试傻瓜插件

**Comment by Colsrch** [comment]
抱歉，两周前没发现这条issue邮件，今天发现close邮件才知道，这里回答下你的这几个问题
1、有关时间戳这些：这个是只会在食用pjax的情况下出现，因为每个版本的缓存都有一个sw缓存编号，而由于pjax的特性，这个缓存编号便会显示出来，不用pjax是没有缓存编号的。
2、它的缓存范围是可以自己控制的，修改这里面的就可以
``` yml
staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
```
3、关于第三个，我仔细想了想，直接刷新确实不太好，感谢您的建议
